spring:
  application:
    name: zuul-service

server:
  port: 8762

zuul:
  prefix: /api
  routes:
    product-catalog-service:
      path: /catalog/**
      serviceId: product-catalog-service
    pricing-service:
      path: /pricing/**
      serviceId: pricing-service
    audit-trail-service:
      path: /audit/**
      serviceId: audit-trail-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
