# Embedded HTTP (Tomcat) server port
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

spring:
  application:
    name: product-catalog-service

  data:
    # host is the container_name of MongoDB in docker-compose.yml
    mongodb:
      host: mongodb
      port: 27017
      database: products

  cloud:
    stream:
      bindings:
        output:
          destination: input

  rabbitmq:
    addresses: rabbitmq:5672
    username: admin
    password: admin
